[package]
name = "ror_escrow"
version = "0.1.0"
edition = "2021"

[lib]
name = "ror_escrow"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = { version = "0.30.1", features = ["token"] }
